#!/bin/bash
# sortTimingOutput_synth.sh

# Use bash to sort timing output CSV files of synthetic apps produced by MERCATOR.

usage="Usage: $0 <results directory>    NB: Results assumed to be generated by runSynthExps.sh or runBlastExps.sh scripts."

# must have src dir with results files
if [ "$#" -ne 1 ];
then
  echo ${usage}
  exit 1
fi

# check whether src dir exists
srcDir=$1
if ! [ -e ${srcDir} ];
then
  echo "Error: directory ${srcDir} not found."
  exit 1
fi

# check whether src dir is a dir
if ! [ -d ${srcDir} ];
then
  echo "Error: ${srcDir} is not a directory."
  exit 1
fi

## recursively sort all files in src dir; place sorted filed in destination dir
dstDir=${srcDir}_sorted

mkdir -p ${dstDir}
# for each of 4 synthetic apps
for topoDir in ${srcDir}/* 
  do
    if ! [ -d ${topoDir} ];
    then
      echo "Skipping non-dir file ${topoDir} in ${srcDir}..."
    else
      topoDirTail=${topoDir##*/}
      mkdir -p ${dstDir}/${topoDirTail}
  
      for file in ${topoDir}/* 
        do
          newName=${file##*/}
          sort -t',' -g -k2,2 -k1,1 -k3,3 ${file} > ${dstDir}/${topoDirTail}/${newName}
        done
fi
  done

